export { default as Home } from "./Home";
export { default as NotFound } from "./NotFound";
export { default as Quiz } from "./Quiz";
export { default as ScoreSingle } from "./ScoreSingle";
export { default as ScoreMulti } from "./ScoreMulti";
export { default as CreateRoom } from "./CreateRoom";
export { default as Subjects } from "./Subjects";
export { default as Waiting } from "./Waiting";
export { default as LeaderBoard } from "./LeaderBoard";
